export const ProductCategories = [
  { id: 0, name: "Home And Gadgets", link: "home-gadgets" },
  { id: 1, name: "Health And Beauty", link: "health-beauty" },
  { id: 2, name: "Hot Offer", link: "hot-offer" },
  { id: 3, name: "Baby Products", link: "baby-products" },
  { id: 4, name: "Alpha Soap", link: "alpha-soap" },
];

export const productMock = [
  {
    id: "0",
    stock: 10,
    category: "Hot Offer",
    name: "Italian Diamond 925 sterling silver Women's Wedding rings",
    price: 1000,
    discountPrice: 500,

    discountPercentage: 50,
    image: "/product mock/diamond.jpg",
  },
  {
    id: "1",
    stock: 10,
    category: "Hot Offer",
    name: "IHousehold Kitchen Washing Liquid Dish Brush",
    price: 600,
    discountPrice: 420,
    discountPercentage: 20,
    image: "/product mock/pan_washer.png",
  },
  {
    id: "2",
    stock: 10,
    category: "Hot Offer",
    name: "Food Sealing Machine",
    price: 2300,
    discountPrice: 1600,
    discountPercentage: 35,
    image: "/product mock/vacuem.jpg",
  },
  {
    id: "3",
    stock: 10,
    category: "Hot Offer",
    name: "আকুপাংচার ফুট মেসেজ সুজ",
    price: 1450,
    discountPrice: 899,
    discountPercentage: 30,
    image: "/product mock/slides.png",
  },
  {
    id: "4",
    stock: 10,
    category: "Hot Offer",
    name: "T9 Electric Rechargeable Trimer",
    price: 1250,
    discountPrice: 750,
    discountPercentage: 20,
    image: "/product mock/trimmer.jpg",
  },
  {
    id: "5",
    stock: 10,
    category: "Hot Offer",
    name: "Profissional Hot Combs Anti-Scalding Hair Straightener Brush Ceramic Hair Curler Heated Electric Smart Brush Hair Straightener",
    price: 1550,
    discountPrice: 930,
    discountPercentage: 30,
    image: "/product mock/straightner.png",
  },
];

export const bangladeshDistricts = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barishal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chapainawabganj",
  "Chattogram",
  "Chuadanga",
  "Cox's Bazar",
  "Cumilla",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokati",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];
